// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITD13iVcntlithBwhnMNJKg-sOE7XtfQ',
    appId: '1:532653013252:android:4f9279d667c81bf10c3851',
    messagingSenderId: '532653013252',
    projectId: 'plant-project-202520262027',
    storageBucket: 'plant-project-202520262027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiIhXoopzKr6_qXb-0Sicng_Ev4pRyn-o',
    appId: '1:532653013252:ios:d36f59f849463c2a0c3851',
    messagingSenderId: '532653013252',
    projectId: 'plant-project-202520262027',
    storageBucket: 'plant-project-202520262027.firebasestorage.app',
    androidClientId: '532653013252-bl2ihvnlu53l0rtl7cq53lhkottd3mga.apps.googleusercontent.com',
    iosClientId: '532653013252-ff16083mjndllmb5eh7cspmal1ednuot.apps.googleusercontent.com',
    iosBundleId: 'com.example.floraMateApp',
  );
}
